// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfE-wyAPBWOGcTWFt1rHEOQZBuwhRGkbQ',
    appId: '1:537545122887:web:f94613fa318cb50a57fd62',
    messagingSenderId: '537545122887',
    projectId: 'notification-ad7d0',
    authDomain: 'notification-ad7d0.firebaseapp.com',
    storageBucket: 'notification-ad7d0.appspot.com',
    measurementId: 'G-E6WZS14KMQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXNSbQ6vW8shFDBWBv_Cgc3X4NLDEQKdc',
    appId: '1:537545122887:android:acd5b7e26278455b57fd62',
    messagingSenderId: '537545122887',
    projectId: 'notification-ad7d0',
    storageBucket: 'notification-ad7d0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCskSXwfuwrwztLSbPwLAEKeoOQGcQHutw',
    appId: '1:537545122887:ios:5bdc02be738d0d4857fd62',
    messagingSenderId: '537545122887',
    projectId: 'notification-ad7d0',
    storageBucket: 'notification-ad7d0.appspot.com',
    iosClientId: '537545122887-2cqlrrao42ghouecjhuhrldbn45532ju.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseNotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCskSXwfuwrwztLSbPwLAEKeoOQGcQHutw',
    appId: '1:537545122887:ios:14c81fe49a1a445a57fd62',
    messagingSenderId: '537545122887',
    projectId: 'notification-ad7d0',
    storageBucket: 'notification-ad7d0.appspot.com',
    iosClientId: '537545122887-spmkuqnv7067phllg9de9if8jo0s68j7.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseNotification.RunnerTests',
  );
}
